version: 2.1

orbs:
  gh-release: escaletech/gh-conventional-release@0.1

jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test -- --coverage

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters: { branches: { ignore: master }, tags: { ignore: /.*/ } }

  release:
    jobs:
      - gh-release/create-release:
          filters: { branches: { ignore: /.*/ }, tags: { only: /v.+/ } }
          context: github-create-release
